version: "3"

services:
  db:
#    restart: always
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - openxpkidb:/var/lib/mysql
      - openxpkidbsocket:/var/run/mysqld/
      - ${OPENXPKI_CONFIG_PATH}/contrib/sql/schema-mariadb.sql:/docker-entrypoint-initdb.d/schema-mariadb.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  openxpki-server:
#    restart: always
    image: whiterabbitsecurity/openxpki3
    command: /usr/bin/openxpkictl start --no-detach
    volumes:
      - ${OPENXPKI_CONFIG_PATH}:/etc/openxpki
      - openxpkilog:/var/log/openxpki
      - openxpkisocket:/var/openxpki/
      - openxpkidbsocket:/var/run/mysqld/
      # this will not work on all OS
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
        - db

  openxpki-client:
#    restart: always
    image: whiterabbitsecurity/openxpki3
    command: /usr/bin/start-apache
    ports:
      - "4080:80/tcp"
      - "4443:443/tcp"
    volumes:
      - ${OPENXPKI_CONFIG_PATH}:/etc/openxpki
      - openxpkilog:/var/log/openxpki
      - openxpkisocket:/var/openxpki/
      - openxpkidbsocket:/var/run/mysqld/
    depends_on:
        - openxpki-server

volumes:
  openxpkidb:
  openxpkisocket:
  openxpkidbsocket:
  openxpkilog:

